"""Alembic migration environment.

The database URL is read from ``DATABASE_URL`` rather than ``alembic.ini`` so
that no credentials live in the repository (see ``.env.example``).

``target_metadata`` is ``None``: there are no SQLAlchemy models yet, and
migrations are hand-written rather than autogenerated. When models land
(M1+), point this at their ``MetaData`` to enable ``alembic revision
--autogenerate``.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def _database_url() -> str:
    """Return the configured database URL, or explain how to set one."""
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. Copy .env.example to .env and export it, "
            "or run `make migrate`, which supplies the local default."
        )
    return url


def run_migrations_offline() -> None:
    """Emit migration SQL to stdout without connecting to a database.

    Used by ``alembic upgrade head --sql``, which lets the migrations be
    tested in CI where no Postgres is running.
    """
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    # The engine is built directly from the URL rather than through
    # config.set_main_option, which would treat a '%' in a password as
    # ConfigParser interpolation syntax.
    connectable = create_engine(_database_url(), poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()
    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
